CREATE DATABASE IF NOT EXISTS MyApp;
USE MyApp;

DROP TABLE IF EXISTS Credential;
DROP TABLE IF EXISTS User;

-- DATABASE SCHEMA DEFINITIONS
    --id CHAR(32) unique not null default sys_guid() PRIMARY KEY,
CREATE TABLE IF NOT EXISTS User (
    id BINARY(16) UNIQUE NOT NULL DEFAULT UNHEX(SYS_GUID()) PRIMARY KEY,
    email VARCHAR(512) UNIQUE NOT NULL,
    firstName VARCHAR(512),
    lastName VARCHAR(512),
    token BINARY(16) DEFAULT UNHEX(SYS_GUID()),
    createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastModifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    --user_id CHAR(32),
CREATE TABLE IF NOT EXISTS Credential (
    id BINARY(16) UNIQUE NOT NULL DEFAULT UNHEX(SYS_GUID()) PRIMARY KEY,
    userId BINARY(16),
    token VARBINARY(4098),
    type VARCHAR(32),
    active BOOLEAN DEFAULT true,
    expirationDate TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 MINUTE),
    FOREIGN KEY(userId) REFERENCES User(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SHOW WARNINGS;